server:
  port: 8090

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      file-size-threshold: 10MB

  datasource:
    url: jdbc:mysql://192.168.242.148:3306/bs?characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


logging:
  path: ./logs/bs
  logging: root=INFO

custom:
  jwt:
    secret:  123592qwesgxw
    expiration: 3600
    header: jwtheadername
  es:
    address: 192.168.242.131
    port: 9200
